name: Hostinger VPS Node Server

on:
  push:
    branches:
      - main  # Or 'master', check your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          # 1. Go to the project folder
          cd ~/bukizz_node_server

          # 2. Pull the latest code from GitHub
          git reset --hard
          git pull origin main

          # 3. Install dependencies and Build
          # (We use --force sometimes if there are version conflicts)
          npm install

          # 5. Restart Backend (Optional, but good practice)
          pm2 restart all --update-env
          
          echo "Deployment Complete!"